apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: index-page-1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
---
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>ECS Pod</title>
    </head>
    <body>
        <p style="font-size: 40px;">HOL ECS deployed NGINX site<p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: index-page-1
