---
apiVersion: v1
kind: Namespace
metadata:
  name: wind-turbine-demo
  labels:
    app: wind-turbine-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: kmikholap/wt-frontend-ui:v12
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  type: NodePort
  selector:
    app: frontend-ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: kmikholap/wt-data-processor:latest
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor
  namespace: wind-turbine-demo
spec:
  selector:
    app: data-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:latest
        ports:
        - containerPort: 8086
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: root
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: wt_co_secret_password
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: wt-co
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: wind_turbine
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: "0"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: wttoken
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: wind-turbine-demo
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-server
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcua-server
  template:
    metadata:
      labels:
        app: opcua-server
    spec:
      containers:
      - name: opcua-server
        image: kmikholap/wt-opcua-server:latest
        ports:
        - containerPort: 4840  
---
apiVersion: v1
kind: Service
metadata:
  name: opcua-server
  namespace: wind-turbine-demo
spec:
  selector:
    app: opcua-server
  ports:
  - protocol: TCP
    port: 4840  
    targetPort: 4840
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: kmikholap/wt-rabbitmq:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 15672   # Management UI
        - containerPort: 5672    # AMQP
        - containerPort: 1883    # MQTT
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_NODENAME
          value: "rabbit@localhost"
        - name: RABBITMQ_PLUGINS
          value: "rabbitmq_management rabbitmq_mqtt"
        volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: wind-turbine-demo
data:
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.listener.port = 15672
    mqtt.listeners.tcp.default = 1883
    mqtt.default_user = guest
    mqtt.default_pass = guest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: wind-turbine-demo
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30011
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30012
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 30013
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
      - name: sensor-simulator
        image: kmikholap/wt-sensor-sim:v1
        imagePullPolicy: Always
        env:
        - name: MQTT_BROKER
          value: "rabbitmq"
        - name: MQTT_PORT
          value: "1883"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: kmikholap/wt-backend:v11
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_TOKEN
          value: "wttoken"
        - name: INFLUXDB_ORG
          value: "wt-co"
        - name: INFLUXDB_BUCKET
          value: "wind_turbine"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: wind-turbine-demo
spec:
  selector:
    app: backend-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30004
  type: NodePort
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-us-east-site-01-e101
  namespace: wind-turbine-demo
data:
  SITE_NAME: "us-east-onshore-site-01"
  TURBINE_NAME: "turbine-e101"
  TURBINE_INFO: "<b>GaleForce XT</b><br>Rotor:220m<br>Blade:107m<br>Height:260m<br>Capacity:12-14MW"
  WEBSOCKET_URL: "ws://192.168.123.213:30004/ws"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: wind-turbine-demo
spec:
  template:
    spec:
      containers:
      - name: backend-api
        env:
        - name: SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-us-east-site-01-e101
              key: SITE_NAME
        - name: TURBINE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-us-east-site-01-e101
              key: TURBINE_NAME
        - name: TURBINE_INFO
          valueFrom:
            configMapKeyRef:
              name: backend-us-east-site-01-e101
              key: TURBINE_INFO
        - name: WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: backend-us-east-site-01-e101
              key: WEBSOCKET_URL
---
