---
apiVersion: v1
kind: Namespace
metadata:
  name: wind-turbine-demo
  labels:
    app: wind-turbine-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: kmikholap/wt-frontend-ui:v12
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  type: NodePort
  selector:
    app: frontend-ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: kmikholap/wt-data-processor:latest
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor
  namespace: wind-turbine-demo
spec:
  selector:
    app: data-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
