apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: vm-small
spec:
  hardware:
    cpus: 2
    memory: 2Gi
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: photon-vm-static-ip
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: vm-small
  imageName: 192.168.123.254/downloads/photon-vm-static-ip.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
