apiVersion: v1
kind: Namespace
metadata:
  name: home-page
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: home-page
  namespace: home-page
spec:
  selector:
    matchLabels:
      app: home-page
  replicas: 1
  template:
    metadata:
      labels:
        app: home-page
    spec:
      containers:
      - name: home-page
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: index-page-1
---
apiVersion: v1
kind: Service
metadata:
  name: home-page-service
  namespace: home-page
spec:
  selector:
    app: home-page
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
---
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
       <title>Edge Compute Stack (ECS) Demo</title>
       <style>
       html { color-scheme: light dark; }
       body { width: 50em; margin: 0 auto;
       font-family: Tahoma, Verdana, Arial, sans-serif; }
       </style>
    </head>
    <body>
    <h1>Hello from Edge Compute Stack (ECS)!</h1>
    <h2>Webpage Version 1.0</h2>
    <p>If you see this page, the web server is successfully installed and working. This webpage is running from a nginx container hosted on the ECS server or device.</p>

    <p>The ECS Product page is located here:
    <a href="https://www.vmware.com/products/software-defined-edge/edge-compute/stack">VMware ECS Product Page</a>.<br/>
    For online documentation please refer to:
    <a href="https://docs.vmware.com/en/VMware-Edge-Compute-Stack/index.html">VMware ECS Online Documentation</a>.<br/>
    The VMware Edge Ochestrator (VECO) launchpad is located here:
    <a href="https://ecs.orchestrator.vmware.com/#/configure/launchpad">VMware VECO Launchpad</a>.</p>

    <p>The web page is hosted on port 31000.<br/>
    The Grafana with Prometheus dashboard is hosted on port 30001 located here: 
    <a href="http://192.168.123.213:30001">Grafana with Prometheus</a>.<br/>
    The kubernetes dashboard is hosted on port 30002 located here: 
    <a href="http://192.168.123.213:30002">Kubernetes Dashboard</a>.<br/>
    The Wind Turbine Demo dashboard is hosted on port 30005 located here: 
    <a href="http://192.168.123.213:30005">Wind Turbine Demo Dashboard</a>.<br/>
    The Computer Vision dashboard is hosted on port 30006 located here: 
    <a href="http://192.168.123.213:30006">Computer Vision App</a>.<br/>
     The Object Detection App is hosted on port 30850 located here: 
    <a href="http://192.168.123.213:30850">Object Detection App</a>.<br/>
    The Photon Linux Demo dashboard is hosted on port 80 located here: 
    <a href="http://192.168.123.91:80">Photon Linux</a>.<br/>
    </p>

    <p><em>Thank you for reviewing the VMware by Broadcom ECS demo.</em></p>
    <p>Version 1.0</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: index-page-1
  namespace: home-page
