apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: photon-vm-small
spec:
  hardware:
    cpus: 2
    memory: 2Gi
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: photon-linux-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: photon-vm-small
  imageName: 192.168.123.254/downloads/photon-web-linux-vm.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    transport: CloudInit
    configMapName: photon-linux-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photon-linux-config
  namespace: default
data:
  networkconfig: |
        version: 2
        ethernets:
            eth0:
                dhcp: "false"
                addresses:
                    - 192.168.123.215/24
                nameservers:
                    addresses:
                        - 192.168.123.1
                routes:
                    - to: 0.0.0.0/0
                      via: 192.168.123.1 
